### ISSUE TITLE
Генерация меандра с указанной частотой на других пинах

### ISSUE THREAD

**Issue by IhorNehrutsa** [GyverLibs/GyverPWM#2]
Нужны аналогичные функции для других пинов

/* Генерация меандра с указанной частотой на пине 9 */
float PWM_square_D9(float frequency)

**Comment by GyverLibs** [comment]
Можно запустить в любом другом режиме через обычный ШИМ с заполнением 50%

**Comment by IhorNehrutsa** [comment]
Да, так и делаю, но API библиотеки должно быть полным.
Для новичков не очевидно, что на других пинах это работает тоже.
Это будет раздражать пользователей.

**Comment by GyverLibs** [comment]
> Для новичков не очевидно, что на других пинах это работает тоже.

Это не работает на других пинах, функция сделана только для первого таймера. Работать чисто с меандром лучше при помощи библиотеки GyverTimers, здесь это сделано для примера
