### ISSUE TITLE
Лагает ШИМ 

### ISSUE THREAD

**Issue by hikayamasan353** [GyverLibs/GyverPWM#7]
Здравствуйте. Когда я при нажатии на кнопку подаю ШИМ частоту на контакт, то она появляется не сразу а через некоторое время. Когда кнопка отпущена, то ШИМ глушится не сразу.

Вот пример кода:
#include <GyverPWM.h>

void setup()
{
   pinMode(2, INPUT); // 2 контакт - кнопка
   pinMode(9, OUTPUT); //контакт 9, таймер 1
}
void loop()
{
   if(digitalRead(2)==HIGH)
   {
      PWM_frequency(9, 440, FAST_PWM);
      analogWrite(9, 512);
   }
   else
   {
      PWM_detach(9);
      digitalWrite(9, LOW);
   }
}

Мне бот ChatGPT сказал что это может быть из-за плохого контакта между проводом и контактом.

**Comment by GyverLibs** [comment]
Ужасный код. Настройку частоты нужно делать однократно , например в setup. Шим тоже не нужно постоянно вызывать функцию, нужно однократно по событию. Кнопку нужно обработать корректно, отдельно нажатие отдельно отпускание, с гашением дребезга
